### PR TITLE
Improved target reference generation

### LINKED ISSUE #421: args is not defined at mg_strip_punctuation when switching chart types
I'm getting an `args is not defined` error on [this line](https://github.com/mozilla/metrics-graphics/blob/34e56c4a387940c3e5e58a458062389a8110c4e5/src/js/misc/utility.js#L158).

I'm loading a blank chart (with `chart_type` set to `missing-data`) which works fine. However, when I set the data in the `options` object, set `chart_type` to `line`, and pass `options` to `MG.data_graphic` I get the `args is not defined` error. This only happens when setting the target to a DOM element selected by class (`$('.chart-area').get(0)`).

### PR DESCRIPTION
**Pull request by dstaley**
This fixes #421 which is an issue using a class selector as the target when switching from a missing chart to a line chart. I'm not sure if it affected any other use case.

All tests are green. I also wrote a test case for this scenario, but I'm not sure what I should assert.
```js
test('Can change from missing chart to line chart using class selector as target', function() {

    var qunit_fixture = document.getElementById('qunit-fixture');
    var chart_area = document.createElement('div');
    chart_area.className = 'chart-area';
    qunit_fixture.appendChild(chart_area);

    var params = {
        target: document.querySelector('.chart-area'),
        chart_type: 'missing-data',
        missing_text: 'In an astral plane that was never meant to fly...'
    };

    MG.data_graphic(params);

    params.data = [{'date': new Date('2014-01-01'), 'value': 12},
                   {'date': new Date('2014-03-01'), 'value': 18}];
    params.chart_type = 'line';

    MG.data_graphic(params);
    // should I assert anything here?
});
```

### CODE REVIEW

**Comment by dandehavilland** [comment]
Thanks for the fix, looks good for what we have, but I think our underlying code here is a little broken.

I'd argue that `mg_strip_punctuation` should only be responsible for actually stripping punctuation (so it shouldn't need to know about `className` and `nodeName`) and break this out to have a function which extracts/generates a unique reference for the target, e.g. `target_ref(args.target)`, which would use `mg_strip_punctuation` internally. I've just pushed something up a PR to your PR that is more along these lines.

**Comment by hamilton** [comment]
Yeah I think that's sensible. I believe I made that change to ```mg_strip_punctuation``` to make things work, in haste :)

**Comment by almossawi** [comment]
Thanks @dstaley, @dandehavilland.

@hamilton Ok to merge?

**Comment by hamilton** [comment]
go for it! Thanks for the contributions y'all ~

**Pull request merged**
