### PR TITLE
Updating the version of node on travis so that ES6 is supported

### PR DESCRIPTION
**Pull request by lobax**
Attempting to change the version of node used on travis as per the suggestion given by @wlach in issue #815

### CODE REVIEW

**Comment by lobax** [comment]
The tests are not preformed by preformed on travis. It produces the following error and then stalls until it times out: 

```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (/home/travis/build/DD2480-G9/metrics-graphics/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/travis/build/DD2480-G9/metrics-graphics/node_modules/express/lib/response.js:170:12)
    at /home/travis/build/DD2480-G9/metrics-graphics/node_modules/testem/lib/server/index.js:93:27
    at Layer.handle_error (/home/travis/build/DD2480-G9/metrics-graphics/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/travis/build/DD2480-G9/metrics-graphics/node_modules/express/lib/router/index.js:315:13)
    at /home/travis/build/DD2480-G9/metrics-graphics/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/travis/build/DD2480-G9/metrics-graphics/node_modules/express/lib/router/index.js:335:12)
    at next (/home/travis/build/DD2480-G9/metrics-graphics/node_modules/express/lib/router/index.js:275:10)
```

**Comment by wlach** [comment]
When in doubt, try upgrading node packages. :) Could you try upgrading the version of `testem` to 2.0.0 and see if it helps?

https://github.com/mozilla/metrics-graphics/blob/4f4f702fcd4cebd19ee894e89e8860afa11f6e47/package.json#L59

**Comment by RickardBjorklund** [comment]
Applying the changes @wlach suggested in #815 and #816 (specifying node version in travis.yml and upgrading node package) makes travis run again https://github.com/mozilla/metrics-graphics/pull/816/commits/13c71a16f690f30b86e56bb794b216542c3cd2a2 however when applying a trivial ES5 to ES6 change https://github.com/mozilla/metrics-graphics/pull/816/commits/8ae73fb492d121654a9f49b7cbefb2900f66b919 travis crashes again. Applying the same change and running the test suite locally with gulp test works well and no test crashes or fails.

**Comment by lobax** [comment]
My guess is that the tests on the CI fail because Phantomjs 2.1 does not support ES6. [Development on PJS seems rather stale and they do not support ES6 yet](https://github.com/ariya/phantomjs/issues/15287), so perhaps testing should be done in a different way.

**Comment by wlach** [comment]
@lobax @RickardBjorklund argh that sucks, I didn't know phantomjs didn't support es6

In any case, we should probably move to doing headless browser testing using Firefox and Chrome. Travis has some general advice on how to do this:

https://docs.travis-ci.com/user/gui-and-headless-browsers/

I'm not 100% sure how to hook this up to testem, but I can't imagine it's that hard. For a first pass, I think we can settle for testing using either Firefox *or* Chrome, unless it's super trivial to do both. We can always add support for the other in a follow-up.

Thank you for your patience on this!

**Comment by lobax** [comment]
@wlach It now runs fine on Chrome instead of phantomjs. 

Please double check the rows I added to the travis.yml file though, as those changes where needed to get chrome to run on our fork but it seemed to work fine without them here.

**Comment by wlach** [comment]
Just squashed this into one commit and landed it. Thank you!

**Pull request merged**
