### PR TITLE
Remove the dependency on jQuery

### PR DESCRIPTION
**Pull request by almossawi**
This PR follows up on the great work by @soyuka from about a month ago (see #132). It removes jQuery from everywhere--modulo buttons, dropdowns and tooltips--replacing them with D3 functions wherever appropriate, to facilitate readability, and native functions everywhere else. I'd feel more comfortable merging this once a couple of people have reviewed it.

Will follow up with that last bit in the coming few days.

@soyuka I took on the task since we have it planned for the Feb 15 release, and I didn't want to inconvenience you in case you had your hands full with other work.

### CODE REVIEW

**Comment by soyuka** [comment]
@almossawi I'm really sorry but I've got a lot on my hands these pasts (and upcoming) months! Hope that you've merge what I already did in the mentioned PR ;). I can rebase my branch if you need too!

**Comment by almossawi** [comment]
@soyuka Not to worry :) Yes, if you wouldn't mind rebasing, that would be great. I'd prefer merging your PR, of course, so that your contribution is part of the codebase. I can then take care of the newer code that's been added since.

**Comment by soyuka** [comment]
It's a mess my branch is far away from the current master; a lot has been done since, that's great btw! I'm not sure if it'd be better to `rebase` or to `merge` at this point. I'll try to take the time to do this in the cleanest way possible, any help appreciated!

**Comment by almossawi** [comment]
@soyuka Not a problem, I can take care of it. I'll do a manual merge tomorrow morning :+1:

**Pull request closed without merging**
