### PR TITLE
Groundwork for extensibility (WIP)

### PR DESCRIPTION
**Pull request by dandehavilland**
All tests are passing, and everything _looks_ to be working fine, but as this is quite a large PR, this could do with a thorough review.

It was mostly just a case of wrapping the charts in closures to avoid polluting with globals. The diffs are very misleading because of this.

- All chart-specific logic (descriptor, defaults, initializer etc.) is now in the corresponding `src/js/charts/*.js` file.
- Rewritten the intitializer into the `chart#init` method (happy to discuss this if you'd prefer to keep it separate).
- There was an issue with scope when defining and initializing charts: the global `charts` object was `this` for the chart function definitions so everything was leaking and being overwritten each time a chart was initialized. I've rewritten the init logic from the equivalent of `chart.line()` to `new chart.line()` in order to maintain the correct scope.
- [Added `MG.register`](https://github.com/dandehavilland/metrics-graphics/blob/fcc2aea1e6e3854b8683e454dfaf4637f7f49e3a/src/js/common/register.js) and [altered `data_graphic`](https://github.com/dandehavilland/metrics-graphics/blob/fcc2aea1e6e3854b8683e454dfaf4637f7f49e3a/src/js/common/data_graphic.js#L122) to lookup charts using the same mechanism. (Turned out to be a lot simpler than I'd imagined).

### CODE REVIEW

**Comment by almossawi** [comment]
@dandehavilland This is looking great. Thank you for taking the time to work on it.

One comment: Chart-specific defaults aren't taking precedence over global defaults and user-specified args, it seems, because of the order in which defaults are merged. So for instance, the ``missing`` chart's left margin ends up being 50 instead of 10. I can take a look at that tomorrow morning.

Also, a minor comment: We'll need to load ``register.json`` in ``examples/dev.htm`` :+1:

**Comment by dandehavilland** [comment]
Thanks @almossawi - I'll fix those issues now.

I've also got a few things left to resolve before this can merge so I'll update this later today.

**Comment by dandehavilland** [comment]
Those are now fixed - let's keep this branch running in parallel with master for a while. I'm setting up a [sample extension](/dandehavilland/mg-sample-extension) to determine if, and how well, this will work.

**Comment by dandehavilland** [comment]
@almossawi  A quick update: I've built a few MG add-ons for a private project and this setup seems to work quite well. I should hopefully find some time over the next few days to rebase this and put together a test repo for you to see how it's working.

**Comment by almossawi** [comment]
@dandehavilland Thanks for the update. This will be a wonderful addition to the library. :+1: 

On a possibly related note, we'll likely be moving the release date for v2.3 to a week later. We had some end-of-quarter deliverables that took up most of our time and so we didn't get a chance to work on any of the issues planned for v2.3.

**Comment by dandehavilland** [comment]
Hi - I ended up quite busy recently so this is arriving a little later than I'd hoped.

I've put a basic example up of [two](http://github.com/dandehavilland/mg-color-scale/) [extensions](http://github.com/dandehavilland/mg-line-brushing/) in action [here](http://dandehavilland.github.io/mg-with-extensions/). 

[mg-color-scale](http://github.com/dandehavilland/mg-color-scale/) extrapolates a scale of line colours based on some predfined CSS rules.

[mg-line-brushing](http://github.com/dandehavilland/mg-line-brushing/) adds simple drag-to-zoom functionality to the line chart.

The extensions, as well as the general blueprint for an extension, are still in need of some work, but with these examples I hope you get a good idea of how this will work.

The file to look at, regarding the hooks implementation, is [hooks.js](https://github.com/dandehavilland/metrics-graphics/blob/a4d3ff8cea8562ffffd2ed7359c7b8ff2bbe7389/src/js/common/hooks.js), and you can see how I use `call_hook` in [line.js](https://github.com/dandehavilland/metrics-graphics/blob/a4d3ff8cea8562ffffd2ed7359c7b8ff2bbe7389/src/js/charts/line.js#L491) which then corresponds to `add_hook` [here](https://github.com/dandehavilland/mg-line-brushing/blob/a8c70813291b05f7eff52640847e48629a489781/src/js/hooks.js#L268).

Thus far, I've only dropped in hooks where I've needed them for development of the aforementioned addons.

**Comment by almossawi** [comment]
Hi @dandehavilland,

Thank you. I'll be sure to take a look at that tomorrow.

**Comment by almossawi** [comment]
@dandehavilland This works great. I got a chance to play with it this morning, and I'll spend some time creating an extension or two next. It's looking really nice :+1:

**Comment by dandehavilland** [comment]
I should have mentioned before that you can fork/clone this [sample extension](/dandehavilland/mg-sample-extension) (also WIP) as a starting point for your extensions. Provides a foundation for testing and a local dev server.

**Comment by dandehavilland** [comment]
@almossawi Hi - did you get a chance to try build some extension? I've just rebased against `master` - which took a while as we've diverged quite a lot in this branch - and I think it can be merged, provided yourself and @hamilton are happy with it? In the meantime, I'll pad out `HOOKS.md` with some more detail on the process of extending.

**Comment by almossawi** [comment]
Hi @dandehavilland, Thank you for taking the time to rebase against master--it must have been quite tedious.

Yes indeed, I did get a chance to play with it and plan to share some extensions in time for the next release. Some other pressing work has been consuming nearly all of my time as of late, though that ought to be coming to a happy conclusion soon. I'll go ahead and merge your PR :)

**Pull request merged**
