### PR TITLE
added option to center title over entire chart

### PR DESCRIPTION
**Pull request by Ezekiel-DA**
As detailed in #651, this is an attempt to add an option to center the chart title over the entire chart, margins included. The option is center_title_full_width and defaults to false.

If accepted I'll go ahead and add it to the wiki too !

### CODE REVIEW

**Comment by Ezekiel-DA** [comment]
`gulp test` passes locally; not sure why tests are failing in Travis, looks like PhantomJS didn't even start.

**Comment by almossawi** [comment]
Thanks 👍

**Comment by Ezekiel-DA** [comment]
Thanks for merging !

I've added the new option to the wiki. Let me know if you want me to add a mention that this is only available in master and not in 2.9, or to remove this entirely until it is available in a released version.

(BTW : the npm package seems to be a little out of date; it is still listing 2.8 as the most recent instead of 2.9)

**Comment by almossawi** [comment]
Wonderful. I've added a note to the wiki and published 2.9 to npm--thanks, that was an oversight.

**Pull request merged**
