### PR TITLE
add .defined for drawing lines, makes missing data look nicer!

### PR DESCRIPTION
**Pull request by birdage**
@almossawi in response to https://github.com/mozilla/metrics-graphics/issues/429. Handles rendering missing data in lines differently to the current implementation. One hiccup might be the `return d.value` depending on what has been set, i think there might be a better way. All tests pass.

### CODE REVIEW

**Comment by almossawi** [comment]
Thank you. I'll be sure to take a look at this on Monday. :+1:

**Comment by birdage** [comment]
@almossawi no worries, seems there is a merge conflict now, haha! just a different take on missing data

**Comment by hamilton** [comment]
Hey @birdage! Thank you for the PR. It's a much more manageable way of doing things than we had before. We're going to 'reject' it since we had to do a bunch of refactoring, but we essentially used what you had.

**Comment by almossawi** [comment]
#449

**Comment by birdage** [comment]
@hamilton no worries! glad to help!

**Pull request closed without merging**
